theme: jekyll-theme-cayman #(Bright, modern blue/green)
# theme: jekyll-theme-slate #(Dark, technical look)
# theme: jekyll-theme-architect #(Clean, structured layout)
# theme: jekyll-theme-merlot #(Elegant, dark red tones)
