# theme: jekyll-theme-cayman #(Bright, modern blue/green)
# theme: jekyll-theme-slate #(Dark, technical look)
# theme: jekyll-theme-architect #(Clean, structured layout)
# theme: jekyll-theme-merlot #(Elegant, dark red tones); following are dark themes...
# theme: jekyll-theme-hacker
# theme: jekyll-theme-midnight  # programming style
theme: jekyll-theme-tactile
---
---
@import "{{ site.theme }}";

body {
  background-color: black; /* Replace with your desired color hex */
  background-image: none;    /* Some themes like 'Midnight' use gradients; this removes them */
}
